    name: Smart Form App Publish Workflow
    on:
      push:
        branches: ['main']

    jobs:
      publish:
        name: Publish App to Nexus Repository
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            node-version:
            - 20.16
            os:
            - ubuntu-latest
        steps:
          - name: Prepare Checkout
            uses: actions/checkout@v3

          - name: Set Up Node JS
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
              check-latest: false

          - name: Installing Packages
            run: npm install

          - name: Set up npm
            run: |
              echo "registry=https://repository.konsulin.care/repository/smart-forms/" > .npmrc
              echo "//repository.konsulin.care/repository/smart-forms/:_authToken=${{ SECRETS.NPM_TOKEN }}" >> .npmrc

          - name: Publish npm package
            run: npm publish

